spring.application.name=Dpsparcial3

spring.datasource.url=jdbc:mysql://localhost:3306/productosdb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

jwt.secret=f90f0aea6ed3ee6fb26e1be96bc01df00f69e30e522f3de1be80a49f7a6c0142
jwt.expiration=900000